---
title: "Hollarsmith_data"
author: "Wendel Raymond"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Analysis of Hollarsmith et al 2022 data
Exploration of supplemental material data from Hollarsmith et al 2022. Purpose is to refine and characterize for the purposes of ranking kelp threats/stressors.

```{r}
library(tidyverse)

theme_set(theme_classic())
```

### Data
```{r}
## Literature search metadata ##
dat.lit <- read.csv("../Hollarsmith supplemental/ece38510-sup-0001-SupInfo.csv", header = TRUE, stringsAsFactors = FALSE)

## Summarized lit counts with effect directionality ##
dat.lit.counts <- read.csv("../Hollarsmith supplemental/ece38510-sup-0002-TableS1.csv", header = TRUE, stringsAsFactors = FALSE)

## all unique 'driver' aka threats ##
threats <- unique(dat.lit$Direct.stressor)
threats <- c("Salinity", "Nutrients", "Temperature", "Water clarity", "Substrate change", "Contaminants", "Mechanical damage", "Algal competition", "Epiphytes")
```

### Raw literature
Exploration of literature dataset

#### Nereocystis and Macrocystis
```{r}
dat.NerMac <- dat.lit %>% 
  filter(str_detect(Species, "Nereocystis luetkeana") | str_detect(Species, "Macrocystis pyrifera"))

unique(dat.NerMac$Direct.stressor)

NerMac.sum <- dat.NerMac %>% 
  group_by(Species, Direct.stressor, Location.general) %>%
  mutate(citation = Citation) %>%
  summarise(count = n())

NerMac.dir.sum <- dat.NerMac %>% 
  group_by(Direct.stressor, Location.general, Relationship) %>% 
  summarize(count = n())

NerMac.dir.sum$Direct.stressor <- ifelse(NerMac.dir.sum$Direct.stressor == "Substrate change (benthic sediment accumulation)", "Substrate change", NerMac.dir.sum$Direct.stressor)

png(filename = "../Figures/NerMac_LitCounts.png", width = 8, height = 6, units = "in", res = 400)
ggplot(NerMac.dir.sum) +
  geom_col(aes(x = Location.general, y = count, fill = Relationship), position = position_dodge(width = 0.9, preserve = "single")) +
  scale_fill_manual(values = c("#C72C2C", "#2083BD", "#7A6969", "#467019")) +
  xlab("Location") +
  ylab("Count") +
  facet_wrap(~Direct.stressor, ) +
  theme(legend.position = c(0.88, 0.13))
dev.off()
```

